### ISSUE TITLE
Load spinners on page render

### ISSUE THREAD

**Issue by michael-duke** [michael-duke/Space-Travelers-Hub#26]
## React-Group-Project | Space Traveler's Hub
We are a team of 2 Micronauts: @michael-duke @PraisesPJMT

In this issue, we have:

- Assigned the tasks accordingly. Some tasks we will do them together as well.
- Removed Team 3 tasks.
- Link to our [kanban board](https://github.com/michael-duke/Space-Travelers-Hub/projects/1)

Happy reviewing, 😄 🚀

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @michael-duke and @PraisesPJMT,

✔️ All tasks are well created and properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
